<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugSymbols>true</DebugSymbols>
        <DocumentationFile>bin\Release\CliArgsParser.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CliArgsParser.Contracts\CliArgsParser.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\CliArgsParser.nuspec">
        <Link>CliArgsParser.nuspec</Link>
      </Content>
    </ItemGroup>

</Project>
