<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugSymbols>true</DebugSymbols>
      <DocumentationFile>bin\Release\CliArgsParser.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CliArgsParser.Contracts\CliArgsParser.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="4.0.0-dev-02160" />
    </ItemGroup>

</Project>
